c ----------------------------------------------------
c 9th DIMACS Implementation Challenge: Shortest Paths
c http://www.dis.uniroma1.it/~challenge9
c ----------------------------------------------------
c Directed road network of the city of Rome (1999)
c Edge costs are physical distances in meters
c Contributed by: 
c     Gianni Storchi, Univ. Rome "La Sapienza"
c     Paolo Dell'Olmo, Univ. Rome "La Sapienza"
c     Monica Gentili, Univ. Salerno
c Converted in DIMACS Challenge 9 format by:   
c     Umberto Ferraro Petrillo
c     Univ. Rome "La Sapienza"
c ----------------------------------------------------
p sp 3353 8870
a 2958 2959 535
a 1494 1573 77
a 1590 1603 184
a 2634 2635 179
a 1984 1985 22
a 1453 1454 33
a 1453 1450 48
a 697 698 50
a 1447 1453 23
a 2036 2034 71
a 564 566 191
a 707 1439 40
a 360 361 81
a 359 360 182
a 1480 1481 17
a 2833 2814 14
a 1436 1437 56
a 1571 1566 72
a 1568 1571 76
a 1567 1568 90